spring:
  datasource:
    username: Ganesh
    password: Ganesh@123
    url: jdbc:mysql://localhost:3306/mydatabase
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true